baseURL = "https://www.example.org/"
languageCode = "pt-BR"
theme = "aafu"

[params]
    title = "Luiz Fernando"
    author = "Darshan Baral"
    description = "Meu site cv"
    #copyright = "aaa"

    [params.theme]
        # Available themes are 'light', 'dark', and 'pinkish'
        mainTheme = "dark"
        # setting false below will hide 'aafu by darshan' displayed under the profile pic
        showAttribute = false
        singlePage = true

    [params.favicons]
        use = true
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="image.png">
        <link rel="icon" type="image/png" sizes="32x32" href="image.png">
        <link rel="icon" type="image/png" sizes="16x16" href="image.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="image.png">
        '''

    # Profile section
    [params.profile]
        name = "Luiz Fernando"
		tagline = "Coding and Learning 📚 "
		location = "Osasco, SP"
        photo = "Eu.png"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
            class = "fab"
            icon = "fa-linkedin-in"
            url = "https://www.linkedin.com/in/luiz-fernando-patheis-65826019b/"
            title = "LinkedIn"		
        [[params.social.list]]
            class = "fab"
            icon = "fa-github"
            url = "https://github.com/tawliew"
            title = "GitHub"
        [[params.social.list]]
            class = "fab"
            icon = "fa-facebook"
            url = "https://www.facebook.com/profile.php?id=100006895382317"
            title = "Facebook"
        [[params.social.list]]
            class = "fab"
            icon = "fa-instagram"
            url = "https://www.instagram.com/rootsluiz/"
            title = "Instagram"
        [[params.social.list]]
            class = "fab"
            icon = "fa-google"
            url = "mailto:lfluiz.lf@gmail.com"
            title = "Gmail"


    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "education"
    #[[params.showInAccordion]]
    #    item = "publication"
    [[params.showInAccordion]]
        item = "project"
    [[params.showInAccordion]]
        item = "skill"
    [[params.showInAccordion]]
        item = "hobby"

    [params.aboutme]
        title = "Sobre"
        icon = "fas fa-user"
        description = "Olá! tudo bem? Me chamo Luiz Fernando e atualmente sou estudante de **Análise e desenvolvimento de Sistemas** pelo **Instituto Federal de Educação, Ciência e Técnolgia de SP (IFSP).** Gosto de aprender coisas novas e diferentes a todo instante."

    # Experience section
    [params.experience]
        title = "Experiências Profissionais"
        icon = "fas fa-briefcase"

        [[params.experience.list]]
            position = "Técnico em Manutenção de Equipamentos de  Informatica"
            dates = "Jan 2018 - Set 2018"
            link = "http://www.maggion.com.br/2011/"
            company = "Maggion"
            details = '''● Além dos afazeres de Técnico, auxiliou na implementação e configuração de novos servidores da empresa,
                            contribuindo na criação de tarefas e rotinas em servidores da Microsoft
                            (Windows Server), Linux (Centos e Ubuntu Server) e Vmware, tanto na
                            manutenção quanto na comunicação das VMs envolvidas.
                      '''
        [[params.experience.list]]
            position = "Auxiliar Administrativo"
            dates = "Jun 2015 - Dec 2017"
            link = "http://www.maggion.com.br/2011/"
            company = "Maggion"
            details = '''● Experiência em manutenção de computadores, notesbooks, celulares e aparelhos IoT.
                         ● Experiência em recepcionar clientes, funcionários e visitantes (tanto pessoalmente quanto por telefone, E-mail ou Chat), elaborar e organizar documentos, preenchimento de planilhas e Metodologia Ágil.
                      '''

    # Education section
    [params.education]
        title = "Ensinos"
        icon = "fas fa-graduation-cap"

        [[params.education.list]]
            degree = "Análise e desenvolvimento de Sistemas"
            college = "Instituto Federal de Educação, Ciência E Técnolgia de São Paulo (IFSP)"
            dates = "2019 - 2021"
            #thesis_title = "Effect of humans on other humans: a study of human behavior."
            #thesis_link = "#"

    # Publication section
    [params.publication]
        title = "Publications"
        icon = "fas fa-book"
        #The order below determines the order in which the items appear in "Publications" section
        format = ["date", "authors", "title", "journal"]
        #If you don't want to group publications, comment the line below by adding # at the beginning
        types = ["Journal Articles", "Proceedings"]

        [[params.publication.list]]
            title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
            authors = "F Last, F Second, P secondary"
            date = "2018"
            journal = "Journal of Field 52 (16), 9033-9044"
            link = "#"
            type = "Journal Articles"

        [[params.publication.list]]
            title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
            authors = "F Last, F Second, P secondary"
            date = "2018"
            journal = "Journal of Field 52 (16), 9033-9044"
            link = "#"
            type = "Journal Articles"
		
        [[params.publication.list]]
            title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
            authors = "F Last, F Second, P secondary"
            date = "2018"
            journal = "Journal of Field 52 (16), 9033-9044"
            link = "#"
            type = "Proceedings"

    # Project section
    [params.project]
        title = "Projetos"
        icon = "fas fa-project-diagram"

        [[params.project.list]]
            title = "Simon Game"
            url = "https://github.com/Tawliew/Simon-Game"
            description = "Um Simon Game muito simples usando apenas jquery"
        [[params.project.list]]
            title = "Basic Newslatter"
            url = "https://github.com/Tawliew/Basic-Newsletter"
            description = "Um template de NewsLatter feito com express e newly"
        [[params.project.list]]
            title = "Bateria Virtual"
            url = "https://github.com/Tawliew/Bateria-Virtual"
            description = "Uma bateria virtual feita em jquery"
        [[params.project.list]]
            title = "patheis-test"
            url = "https://github.com/Tawliew/patheis-test"
            description = "um site no estilo CtF(capture the flag) **--under development--**"            

    # Skill section
    [params.skill]
        title = "   Habilidades"
        panelId = "skill-panel"
        icon = "fas fa-cogs"


        [[params.skill.list]]
            skill = "Linux"
            skillrating = 50
        [[params.skill.list]]
            skill = "Git"
            skillrating = 50
        [[params.skill.list]]
            skill = "HTML,CSS"
            skillrating = 70
        [[params.skill.list]]
            skill = "JS"
            skillrating = 70
    # Hobby section
    [params.hobby]
        title = "Hobbies"
        icon = "fas fa-gamepad"
		
        [[params.hobby.list]]		
		    hobby = "CfG"
        [[params.hobby.list]]		
		    hobby = "Meditar"
        [[params.hobby.list]]		
		    hobby = "Ajudar pessoas!"
        [[params.hobby.list]]		
		    hobby = "Os Cliches: Série/Filmes/Ler/Jogar"
